data_config:
  train_file: train_api.json
  val_file: dev_api.json
  test_file: dev_api.json
  num_proc: 1
max_input_length: 1024
max_output_length: 1024
training_args:
  # see `transformers.Seq2SeqTrainingArguments`
  output_dir: ./output
  max_steps: 500
  # needed to be fit for the dataset
  learning_rate: 1e-6
  # settings for data loading
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 64
  dataloader_num_workers: 1
  remove_unused_columns: false
  # settings for saving checkpoints
  save_strategy: steps
  save_steps: 100
  # settings for logging
  log_level: info
  logging_strategy: steps
  logging_steps: 1
  # settings for evaluation
  per_device_eval_batch_size: 1
  evaluation_strategy: steps
  eval_steps: 100
  # settings for optimizer
  # adam_epsilon: 1e-6
  # uncomment the following line to detect nan or inf values
  # debug: underflow_overflow
  predict_with_generate: true
  # see `transformers.GenerationConfig`
  generation_config:
    max_new_tokens: 1024
  # set your absolute deepspeed path here
  #deepspeed: ds_zero_2.json
  # set to true if train with cpu.
  use_cpu: false
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
